name: Auto Deploy to Oracle

on:
  push:
    branches:
      - main  # This script runs whenever you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Oracle Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/amg-data
            git pull origin main
            npm install
            pm2 restart amg-bot